# Generated by Django 5.2.3 on 2026-03-09 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('due_date', models.DateTimeField(blank=True, null=True, verbose_name='截止时间')),
                ('status', models.CharField(choices=[('pending', '待办'), ('in_progress', '进行中'), ('completed', '已完成')], default='pending', max_length=20, verbose_name='状态')),
                ('reminder_time', models.DateTimeField(blank=True, null=True, verbose_name='提醒时间')),
                ('is_reminded', models.BooleanField(default=False, verbose_name='是否已提醒')),
            ],
            options={
                'verbose_name': '任务',
                'verbose_name_plural': '任务管理',
            },
        ),
    ]
