# Generated by Django 5.2.3 on 2026-03-09 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_reminder', '0004_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='reminder_period',
            field=models.CharField(choices=[('none', '无'), ('daily', '每天'), ('weekly', '每周'), ('monthly', '每月'), ('yearly', '每年')], default='none', max_length=20, verbose_name='提醒周期'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(default='static/images/头像.png', upload_to='avatars/'),
        ),
    ]
