# Generated by Django 5.2.3 on 2026-03-09 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_reminder', '0005_task_reminder_period_alter_userprofile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='tags',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='标签'),
        ),
    ]
