# Generated by Django 5.2.3 on 2026-03-12 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_reminder', '0007_alter_userprofile_avatar_usersession'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='custom_reminder_days',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='自定义提醒天数'),
        ),
        migrations.AlterField(
            model_name='task',
            name='reminder_period',
            field=models.CharField(choices=[('once', '一次性'), ('daily', '每天'), ('weekly', '每周'), ('monthly', '每月'), ('yearly', '每年'), ('custom', '自定义')], default='once', max_length=20, verbose_name='提醒周期'),
        ),
    ]
