# Generated by Django 5.2.3 on 2026-03-12 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_reminder', '0008_task_custom_reminder_days_alter_task_reminder_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='progress_nodes',
            field=models.TextField(blank=True, null=True, verbose_name='进度节点'),
        ),
    ]
