# Generated by Django 5.2.3 on 2026-03-26 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_reminder', '0009_task_progress_nodes'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='reminder_sound',
            field=models.FileField(blank=True, null=True, upload_to='sounds/'),
        ),
    ]
