# Generated by Django 5.2.3 on 2026-04-10 05:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_reminder', '0010_userprofile_reminder_sound'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['user'], name='idx_task_user'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['user', 'priority'], name='idx_task_user_priority'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['user', 'due_date'], name='idx_task_user_due_date'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['user', 'status'], name='idx_task_user_status'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['reminder_time', 'is_reminded'], name='idx_task_reminder'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['created_at'], name='idx_task_created_at'),
        ),
    ]
