# Generated by Django 5.2.3 on 2026-04-23 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_reminder', '0011_task_idx_task_user_task_idx_task_user_priority_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='progress_nodes',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='进度节点'),
        ),
    ]
