# Generated by Django 5.2.3 on 2026-04-23 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_reminder', '0012_alter_task_progress_nodes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='progress_nodes',
            field=models.JSONField(blank=True, default=list, verbose_name='进度节点'),
        ),
    ]
