# Generated by Django 5.2.3 on 2026-04-23 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_reminder', '0013_alter_task_progress_nodes'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='progress_percentage',
            field=models.IntegerField(default=0, verbose_name='进度百分比'),
        ),
        migrations.AddField(
            model_name='task',
            name='progress_status',
            field=models.JSONField(blank=True, default=list, verbose_name='进度节点状态'),
        ),
    ]
